[package]
name = "esp32_interrupt_blink"
version = "0.1.0"
edition = "v1"

[build]
entry = "src/main.skd"

[numeric]
int = "target"

[native]
sources = ["native/board.c"]
libraries = []
library_paths = []
