use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::pipeline::ToolchainOutput;
use crate::project::ProjectConfig;
use crate::targets::CompilerInvocation;

pub const ESP_IDF_TARGET: &str = "esp32-idf";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EspIdfProject {
    pub root: PathBuf,
    pub generated_c: PathBuf,
    pub artifact: PathBuf,
    pub project_name: String,
}

pub fn stage_esp_idf_project(
    project: &ProjectConfig,
    generated_c: &str,
    build_dir: &Path,
) -> Result<EspIdfProject, String> {
    if !project.native_libraries.is_empty() || !project.native_library_paths.is_empty() {
        return Err(
            "esp32-idf does not accept [native].libraries or library_paths yet; add ESP-IDF component dependencies in a board adapter instead"
                .to_string(),
        );
    }

    let root = build_dir.join(ESP_IDF_TARGET);
    let component_dir = root.join("main");
    fs::create_dir_all(&component_dir)
        .map_err(|error| format!("create {} failed: {error}", component_dir.display()))?;

    let project_name = sanitize_project_name(&project.name);
    let generated_c_path = component_dir.join("skadi_program.c");
    fs::write(&generated_c_path, generated_c)
        .map_err(|error| format!("write {} failed: {error}", generated_c_path.display()))?;

    let mut sources = vec!["skadi_program.c".to_string()];
    for (index, relative) in project.native_sources.iter().enumerate() {
        let source = project.root.join(relative);
        if !source.is_file() {
            return Err(format!(
                "native source '{}' does not exist or is not a file",
                source.display()
            ));
        }
        let extension = source
            .extension()
            .and_then(|value| value.to_str())
            .unwrap_or("c");
        let stem = source
            .file_stem()
            .and_then(|value| value.to_str())
            .unwrap_or("adapter");
        let staged_name = format!(
            "native_{index}_{}.{}",
            sanitize_project_name(stem),
            extension
        );
        let staged_path = component_dir.join(&staged_name);
        fs::copy(&source, &staged_path).map_err(|error| {
            format!(
                "copy native source {} to {} failed: {error}",
                source.display(),
                staged_path.display()
            )
        })?;
        sources.push(staged_name);
    }

    let root_cmake = format!(
        "cmake_minimum_required(VERSION 3.16)\nset(IDF_TARGET \"{}\" CACHE STRING \"ESP-IDF target\")\ninclude($ENV{{IDF_PATH}}/tools/cmake/project.cmake)\nproject({project_name})\n",
        project.embedded.chip
    );
    fs::write(root.join("CMakeLists.txt"), root_cmake)
        .map_err(|error| format!("write ESP-IDF root CMakeLists.txt failed: {error}"))?;

    let source_list = sources
        .iter()
        .map(|source| format!("\"{source}\""))
        .collect::<Vec<_>>()
        .join(" ");
    let component_cmake = format!(
        "idf_component_register(SRCS {source_list} INCLUDE_DIRS \".\" REQUIRES esp_driver_gpio esp_driver_gptimer esp_timer)\n\
target_compile_options(${{COMPONENT_LIB}} PRIVATE -Wno-unused-function -Wno-unused-variable)\n"
    );
    fs::write(component_dir.join("CMakeLists.txt"), component_cmake)
        .map_err(|error| format!("write ESP-IDF component CMakeLists.txt failed: {error}"))?;

    fs::write(
        root.join("README.md"),
        "# Generated Skadi ESP-IDF project\n\nThis directory is regenerated by `skadi-cli embedded prepare` or `skadi-cli build --target esp32-idf`. Edit the Skadi source or its declared native board adapter instead of generated files.\n",
    )
    .map_err(|error| format!("write generated ESP-IDF README failed: {error}"))?;

    let artifact = root.join("build").join(format!("{project_name}.bin"));
    Ok(EspIdfProject {
        root,
        generated_c: generated_c_path,
        artifact,
        project_name,
    })
}

pub fn run_idf(project: &EspIdfProject, commands: &[String]) -> Result<ToolchainOutput, String> {
    let program = std::env::var("SKADI_IDF_PY").unwrap_or_else(|_| "idf.py".to_string());
    let mut args = vec!["-C".to_string(), project.root.display().to_string()];
    args.extend(commands.iter().cloned());
    let invocation = CompilerInvocation {
        program: program.clone(),
        args: args.clone(),
    };
    let output = Command::new(&program).args(&args).output().map_err(|error| {
        format!(
            "failed to start ESP-IDF tool '{}': {error}\nhint: install ESP-IDF 5.4+ and run its export script so idf.py and IDF_PATH are available",
            program
        )
    })?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if !output.status.success() {
        return Err(format!(
            "ESP-IDF command failed (status {}): {} {}\n{}{}",
            output.status,
            program,
            args.join(" "),
            stderr.trim(),
            if stdout.trim().is_empty() {
                String::new()
            } else {
                format!("\nstdout: {}", stdout.trim())
            }
        ));
    }
    Ok(ToolchainOutput {
        invocation,
        status: output.status.to_string(),
        stdout,
        stderr,
    })
}

fn sanitize_project_name(name: &str) -> String {
    let mut result = String::new();
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            result.push(character.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }
    while result.starts_with(|character: char| character.is_ascii_digit()) {
        result.insert(0, '_');
    }
    if result.is_empty() {
        "skadi_app".to_string()
    } else {
        result
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::stage_esp_idf_project;
    use crate::project::ProjectConfig;

    #[test]
    fn stages_reproducible_idf_project_with_native_adapter() {
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        let root = std::env::temp_dir().join(format!("skadi_esp_stage_{stamp}"));
        fs::create_dir_all(root.join("native")).expect("create fixture");
        fs::write(root.join("native/board.c"), "void board_init(void) {}\n")
            .expect("write adapter");
        let project = ProjectConfig {
            root: root.clone(),
            name: "Sensor Blink".to_string(),
            entry: root.join("src/main.skd"),
            int_width: "target".to_string(),
            native_sources: vec!["native/board.c".to_string()],
            native_libraries: Vec::new(),
            native_library_paths: Vec::new(),
            embedded: crate::project::EmbeddedConfig::default(),
        };

        let staged =
            stage_esp_idf_project(&project, "void app_main(void) {}\n", &root.join("build"))
                .expect("stage ESP-IDF project");
        assert_eq!(staged.project_name, "sensor_blink");
        assert!(staged.generated_c.is_file());
        let component = fs::read_to_string(staged.root.join("main/CMakeLists.txt"))
            .expect("read component CMake");
        assert!(component.contains("skadi_program.c"));
        assert!(component.contains("native_0_board.c"));
        assert!(component.contains("REQUIRES esp_driver_gpio esp_driver_gptimer esp_timer"));
        let root_cmake =
            fs::read_to_string(staged.root.join("CMakeLists.txt")).expect("read root CMake");
        assert!(root_cmake.contains("set(IDF_TARGET \"esp32\""));

        fs::remove_dir_all(root).expect("remove fixture");
    }
}
