from pygments.lexer import RegexLexer, words
from pygments.token import Comment, Keyword, Name, Number, Operator, Punctuation, String, Text


class SkadiLexer(RegexLexer):
    """Minimal Pygments lexer for Skadi code blocks."""

    name = "Skadi"
    aliases = ["skadi"]
    filenames = ["*.skd"]

    tokens = {
        "root": [
            (r"\s+", Text),
            (r"//.*?$", Comment.Single),
            (r"/\*", Comment.Multiline, "comment"),
            (r'"', String.Double, "string"),
            (r"'(?:\\.|[^'\\])'", String.Char),
            (
                words(
                    (
                        "fn",
                        "danger",
                        "struct",
                        "label",
                        "tag",
                        "new",
                        "constant",
                        "hide",
                        "local",
                        "allow",
                        "grow",
                        "drop",
                        "direct",
                        "view",
                        "move",
                        "if",
                        "else",
                        "when",
                        "is",
                        "while",
                        "for",
                        "iterate",
                        "as",
                        "loop",
                        "return",
                        "returns",
                        "break",
                        "continue",
                        "pass",
                        "on",
                        "error",
                        "interrupt",
                        "event",
                        "run",
                        "wait",
                        "stop",
                        "stopping",
                        "timed_out",
                        "place",
                    ),
                    suffix=r"\b",
                ),
                Keyword,
            ),
            (
                words(
                    (
                        "Int",
                        "Float",
                        "Bool",
                        "Char",
                        "Text",
                        "String",
                        "Path",
                        "Time",
                        "Duration",
                        "ByteSize",
                        "Angle",
                        "Memory",
                        "Task",
                        "Channel",
                        "Interrupt",
                        "List",
                        "Link",
                        "Canvas",
                        "Window",
                        "Point",
                        "Size",
                        "Vec2",
                        "Vec3",
                        "Vec4",
                        "Color",
                        "Rect",
                        "bool",
                        "char",
                        "i8",
                        "i16",
                        "i32",
                        "i64",
                        "u8",
                        "u16",
                        "u32",
                        "u64",
                        "f32",
                        "f64",
                    ),
                    suffix=r"\b",
                ),
                Name.Builtin,
            ),
            (r"\b\d+(?:ns|us|ms|min|s|h)\b", Number.Other),
            (r"\b\d+(?:kb|mb|gb|tb|b)\b", Number.Other),
            (r"\b\d+(?:\.\d+)?(?:deg|rad)\b", Number.Other),
            (r"\b0[bB][01](?:_?[01])*\b", Number.Bin),
            (r"\b0[oO][0-7](?:_?[0-7])*\b", Number.Oct),
            (r"\b0[xX][0-9A-Fa-f](?:_?[0-9A-Fa-f])*\b", Number.Hex),
            (r"\b\d(?:_?\d)*\.\d(?:_?\d)*\b", Number.Float),
            (r"\b\d(?:_?\d)*\b", Number.Integer),
            (words(("true", "false", "null", "PI", "TAU", "E", "EPSILON"), suffix=r"\b"), Name.Constant),
            (r"\bfs\.(list|read|write|is_dir|join)\b", Name.Builtin.Pseudo),
            (r"\b(?:windows\.open|interrupts\.periodic)\b", Name.Builtin.Pseudo),
            (r"\bmemory\.(?:child|static)\b(?=\s*\()", Name.Builtin.Pseudo),
            (
                r"\b(output|print|input|read|write|len|contains|find|slice|concat|args|now|elapsed|delay|sleep|as_nanoseconds|as_bytes|memory|channel|send|receive|send_for|receive_for|try_send|close|abs|min|max|clamp|floor|ceil|round|sign|trunc|fract|lerp|inverse_lerp|remap|smoothstep|sin|cos|tan|asin|acos|atan|atan2|normalize_angle|sqrt|root|is_nan|is_finite|is_infinite|deg_to_rad|rad_to_deg|as_radians|dot|length|length_sq|normalize|distance|distance_sq|cross|bit_and|bit_or|bit_xor|bit_not|bit_shift_left|bit_shift_right|bit_is_set|bit_set|bit_clear|bit_toggle|bit_write|color|color_hex|rect|canvas)\b(?=\s*\()",
                Name.Builtin,
            ),
            (r"\bmy\b", Name.Variable.Instance),
            (r"==|!=|<=|>=|->|=|<|>|\+|\-|\*|\/|\^|%|\+=|-=|\*=|/=|\+\+|--|\band\b|\bor\b|\bnot\b", Operator),
            (r"[{}()[\],.:;]", Punctuation),
            (r"\b[A-Za-z_][A-Za-z0-9_]*\b", Name),
            (r".", Text),
        ],
        "comment": [
            (r"[^*]+", Comment.Multiline),
            (r"\*/", Comment.Multiline, "#pop"),
            (r"\*", Comment.Multiline),
        ],
        "string": [
            (r'\\.', String.Escape),
            (r"__", String.Interpol),
            (r'"', String.Double, "#pop"),
            (r"[^\\\"]+", String.Double),
        ],
    }
