[package]
name = "esp32_gpio_interrupt"
version = "0.1.0"
edition = "v1"

[build]
entry = "src/main.skd"

[numeric]
int = "target"

[native]
sources = []
libraries = []
library_paths = []

[embedded]
chip = "esp32"
allocation = "static"
task_stack_bytes = 4096
task_priority = 2
task_core = "any"
