#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Builtin {
    Len,
    Contains,
    Find,
    Slice,
    Concat,
    FsList,
    FsIsDir,
    FsJoin,
    Args,
    Output,
    Input,
    Read,
    Write,
    Abs,
    Min,
    Max,
    Clamp,
    Floor,
    Ceil,
    Round,
    Sign,
    Trunc,
    Fract,
    Lerp,
    InverseLerp,
    Remap,
    Smoothstep,
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    NormalizeAngle,
    Sqrt,
    Root,
    IsNan,
    IsFinite,
    IsInfinite,
    DegToRad,
    RadToDeg,
    AsRadians,
    Dot,
    Length,
    LengthSq,
    Normalize,
    Distance,
    DistanceSq,
    Cross,
    Now,
    Elapsed,
    Sleep,
    Delay,
    AsNanoseconds,
    AsBytes,
    AsI8,
    AsI16,
    AsI32,
    AsI64,
    AsU8,
    AsU16,
    AsU32,
    AsU64,
    AsF32,
    AsF64,
    WrappingAdd,
    WrappingSub,
    WrappingMul,
    WrappingNeg,
    BitAnd,
    BitOr,
    BitXor,
    BitNot,
    BitShiftLeft,
    BitShiftRight,
    BitIsSet,
    BitSet,
    BitClear,
    BitToggle,
    BitWrite,
    Color,
    ColorHex,
    Rect,
    Canvas,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BuiltinCategory {
    CoreCollectionText,
    CoreFilesystem,
    CoreIo,
    Math,
    SystemsBits,
    SystemsTime,
    Visual,
}

#[derive(Clone, Copy, Debug)]
pub struct BuiltinSpec {
    pub builtin: Builtin,
    pub name: &'static str,
    pub arity: usize,
    pub category: BuiltinCategory,
    pub enabled: bool,
}

const BUILTIN_SPECS: &[BuiltinSpec] = &[
    BuiltinSpec {
        builtin: Builtin::Len,
        name: "len",
        arity: 1,
        category: BuiltinCategory::CoreCollectionText,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Contains,
        name: "contains",
        arity: 2,
        category: BuiltinCategory::CoreCollectionText,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Find,
        name: "find",
        arity: 2,
        category: BuiltinCategory::CoreCollectionText,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Slice,
        name: "slice",
        arity: 3,
        category: BuiltinCategory::CoreCollectionText,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Concat,
        name: "concat",
        arity: 2,
        category: BuiltinCategory::CoreCollectionText,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::FsList,
        name: "fs.list",
        arity: 1,
        category: BuiltinCategory::CoreFilesystem,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::FsIsDir,
        name: "fs.is_dir",
        arity: 1,
        category: BuiltinCategory::CoreFilesystem,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::FsJoin,
        name: "fs.join",
        arity: 2,
        category: BuiltinCategory::CoreFilesystem,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Args,
        name: "args",
        arity: 0,
        category: BuiltinCategory::CoreIo,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Output,
        name: "output",
        arity: 1,
        category: BuiltinCategory::CoreIo,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Input,
        name: "input",
        arity: 1,
        category: BuiltinCategory::CoreIo,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Read,
        name: "read",
        arity: 1,
        category: BuiltinCategory::CoreIo,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Write,
        name: "write",
        arity: 2,
        category: BuiltinCategory::CoreIo,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Abs,
        name: "abs",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Min,
        name: "min",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Max,
        name: "max",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Clamp,
        name: "clamp",
        arity: 3,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Floor,
        name: "floor",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Ceil,
        name: "ceil",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Round,
        name: "round",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Sign,
        name: "sign",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Trunc,
        name: "trunc",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Fract,
        name: "fract",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Lerp,
        name: "lerp",
        arity: 3,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::InverseLerp,
        name: "inverse_lerp",
        arity: 3,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Remap,
        name: "remap",
        arity: 5,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Smoothstep,
        name: "smoothstep",
        arity: 3,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Sin,
        name: "sin",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Cos,
        name: "cos",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Tan,
        name: "tan",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Asin,
        name: "asin",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Acos,
        name: "acos",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Atan,
        name: "atan",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Atan2,
        name: "atan2",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::NormalizeAngle,
        name: "normalize_angle",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Sqrt,
        name: "sqrt",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Root,
        name: "root",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::IsNan,
        name: "is_nan",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::IsFinite,
        name: "is_finite",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::IsInfinite,
        name: "is_infinite",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::DegToRad,
        name: "deg_to_rad",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::RadToDeg,
        name: "rad_to_deg",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsRadians,
        name: "as_radians",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Dot,
        name: "dot",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Length,
        name: "length",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::LengthSq,
        name: "length_sq",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Normalize,
        name: "normalize",
        arity: 1,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Distance,
        name: "distance",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::DistanceSq,
        name: "distance_sq",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Cross,
        name: "cross",
        arity: 2,
        category: BuiltinCategory::Math,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Now,
        name: "now",
        arity: 0,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Elapsed,
        name: "elapsed",
        arity: 1,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Sleep,
        name: "sleep",
        arity: 1,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Delay,
        name: "delay",
        arity: 1,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsNanoseconds,
        name: "as_nanoseconds",
        arity: 1,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsBytes,
        name: "as_bytes",
        arity: 1,
        category: BuiltinCategory::SystemsTime,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsI8,
        name: "as_i8",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsI16,
        name: "as_i16",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsI32,
        name: "as_i32",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsI64,
        name: "as_i64",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsU8,
        name: "as_u8",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsU16,
        name: "as_u16",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsU32,
        name: "as_u32",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsU64,
        name: "as_u64",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsF32,
        name: "as_f32",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::AsF64,
        name: "as_f64",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::WrappingAdd,
        name: "wrapping_add",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::WrappingSub,
        name: "wrapping_sub",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::WrappingMul,
        name: "wrapping_mul",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::WrappingNeg,
        name: "wrapping_neg",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitAnd,
        name: "bit_and",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitOr,
        name: "bit_or",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitXor,
        name: "bit_xor",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitNot,
        name: "bit_not",
        arity: 1,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitShiftLeft,
        name: "bit_shift_left",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitShiftRight,
        name: "bit_shift_right",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitIsSet,
        name: "bit_is_set",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitSet,
        name: "bit_set",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitClear,
        name: "bit_clear",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitToggle,
        name: "bit_toggle",
        arity: 2,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::BitWrite,
        name: "bit_write",
        arity: 3,
        category: BuiltinCategory::SystemsBits,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Color,
        name: "color",
        arity: 4,
        category: BuiltinCategory::Visual,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::ColorHex,
        name: "color_hex",
        arity: 2,
        category: BuiltinCategory::Visual,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Rect,
        name: "rect",
        arity: 4,
        category: BuiltinCategory::Visual,
        enabled: true,
    },
    BuiltinSpec {
        builtin: Builtin::Canvas,
        name: "canvas",
        arity: 2,
        category: BuiltinCategory::Visual,
        enabled: true,
    },
];

fn spec_for_builtin(b: Builtin) -> Option<&'static BuiltinSpec> {
    BUILTIN_SPECS.iter().find(|s| s.builtin == b)
}

pub fn builtin_from_name(name: &str) -> Option<Builtin> {
    BUILTIN_SPECS
        .iter()
        .find(|s| s.enabled && s.name == name)
        .map(|s| s.builtin)
}

pub fn builtin_arity(b: Builtin) -> usize {
    spec_for_builtin(b).map(|s| s.arity).unwrap_or(0)
}

pub fn builtin_accepts_arity(b: Builtin, actual: usize) -> bool {
    match b {
        Builtin::Output => actual >= 1,
        _ => actual == builtin_arity(b),
    }
}

pub fn builtin_arity_description(b: Builtin) -> String {
    match b {
        Builtin::Output => "at least 1 argument".to_string(),
        _ => format!("{} arguments", builtin_arity(b)),
    }
}

pub fn is_builtin(name: &str) -> bool {
    builtin_from_name(name).is_some()
}

pub fn builtin_category(b: Builtin) -> Option<BuiltinCategory> {
    spec_for_builtin(b).map(|s| s.category)
}
