[package]
name = "package_demo"
version = "0.1.0"
edition = "v1"

[build]
entry = "src/main.skd"

[numeric]
int = "target"

[dependencies]
math_kit = "../math-kit"

[native]
sources = []
libraries = []
library_paths = []
